[package]
name = "header-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
http = "1.0"
thiserror = {version = "2", feauters = ["derive"]}


[lib]
path = "src/lib.rs"

[[bin]]
name = "header-analyzer"
path = "src/main.rs"
